import 'dart:typed_data'; // শুধু এটিই রাখো

import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class CVFullPdfScreen extends StatelessWidget {
  final String name, email, phone, address, summary, skills, education, experience, projects, languages, evaluation;

  const CVFullPdfScreen({
    super.key,
    required this.name,
    required this.email,
    required this.phone,
    required this.address,
    required this.summary,
    required this.skills,
    required this.education,
    required this.experience,
    required this.projects,
    required this.languages,
    required this.evaluation,
  });

  Future<Uint8List> _generatePdf(PdfPageFormat format) async {
    final pdf = pw.Document();

    pw.Widget sectionTitle(String title) => pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 16,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.blue,
      ),
    );

    pw.Widget sectionBody(String content) => pw.Text(
      content,
      style: pw.TextStyle(fontSize: 12, color: PdfColors.black),
    );

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(24),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(name, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Text("$email • $phone"),
              pw.Text(address),
              pw.SizedBox(height: 20),

              sectionTitle("Profile Summary"),
              sectionBody(summary),
              pw.SizedBox(height: 10),

              sectionTitle("Skills"),
              sectionBody(skills),
              pw.SizedBox(height: 10),

              sectionTitle("Education"),
              sectionBody(education),
              pw.SizedBox(height: 10),

              sectionTitle("Experience"),
              sectionBody(experience),
              pw.SizedBox(height: 10),

              sectionTitle("Projects"),
              sectionBody(projects),
              pw.SizedBox(height: 10),

              sectionTitle("Languages"),
              sectionBody(languages),
              pw.SizedBox(height: 10),

              // ✅ Evaluation in Box
              sectionTitle("Evaluation"),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  border: pw.Border.all(color: PdfColors.blue, width: 1),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Text(
                  evaluation,
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.black),
                ),
              ),

              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.Text("Generated by CV Generator (Flutter)", style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("CV Preview")),
      body: PdfPreview(
        build: (format) => _generatePdf(format),
      ),
    );
  }
}
